Add Middleware Ownership
alkemyTech/OT252-Server pull request #115
Opened 2022-08-12 19:54 UTC by Emi912

Added Middleware Ownership

2022-08-15 18:34 UTC, emmanuelranone requested changes
En principio el código del mddle no parece estar mal. Fijate que me estas mandando varias clases más que no tienen nada que ver  con lo pedido en la hsitoria y adicionalmente, falta agregar capturas donde se pueda ver el middleware funcionando

2022-08-17 15:08 UTC, Emi912 commented
![image](https://user-images.githubusercontent.com/80789374/185171545-0a5a8e7b-785d-42ad-a944-4b878e677bc6.png)
Logeado con user id 1015, rol común

Intento borrar un user distinto al que esta logeado 
![image](https://user-images.githubusercontent.com/80789374/185171824-bb94d0e7-16b6-4f09-b407-34cdbf0c7f3b.png)
![image](https://user-images.githubusercontent.com/80789374/185171888-ce474f13-118c-4ca9-bcaf-480f3b500d90.png)

Intento borrar al usuario que esta logeado 
![image](https://user-images.githubusercontent.com/80789374/185175259-0e947493-ce2a-484c-b830-e1525fa1a3a7.png)
![image](https://user-images.githubusercontent.com/80789374/185175306-b84d6ae1-d2a2-45c1-853d-0d0acfe84dda.png)

2022-08-18 11:42 UTC, emmanuelranone requested changes
El desarrollo lo veo bien. Fijate de corregir los conflictos en el merge

2022-08-19 11:34 UTC, emmanuelranone approved these changes

2022-08-19 11:35 UTC, merged