Added Helper Image, Fix Errors
alkemyTech/OT252-Server pull request #41
Opened 2022-07-25 17:34 UTC by Emi912

### **Summary**

- Added Helper Image
- Fix Errors

2022-07-25 21:19 UTC, emmanuelranone requested changes
En general el código lo veo bien. Faltaría agregar capturas

2022-07-25 21:57 UTC, Emi912 commented
![image](https://user-images.githubusercontent.com/80789374/180880611-f3ada24b-96fb-4b2e-9c29-3f1b03ba2912.png)
![image](https://user-images.githubusercontent.com/80789374/180880712-24b0c5a5-65b6-4e50-b36e-ce13ed2c42e7.png)

2022-07-25 23:20 UTC, Emi912 commented
![image](https://user-images.githubusercontent.com/80789374/180890730-59f9a60e-8998-450d-86f3-665c8d371185.png)
Imagen abierta en el navegador

2022-07-26 12:13 UTC, emmanuelranone approved these changes

2022-07-26 12:14 UTC, merged