Feature/us 31
alkemyTech/OT252-Server pull request #51
Opened 2022-07-26 20:01 UTC by LucasfVarela

2022-07-26 23:48 UTC, emmanuelranone requested changes
Falta adjuntar captura del funcionamiento

2022-07-27 20:44 UTC, LucasfVarela commented
![2022-07-27](https://user-images.githubusercontent.com/100593063/181368654-13d55e05-3222-4b07-8974-d8376c5de3a1.png)

2022-07-28 17:13 UTC, emmanuelranone requested changes
La captura que me adjuntas tendría que evidenciar el funcionamiento del endpoint. No simplemente mostrar el controller. Es decir tiene que haber captura en caso de que el login funcione bien y devuelva el token, otra para el caso de que la contraseña sea incorrecta, etc.

Ademas fijate que ene ste pr me estás mandando 19 archivos, de los cuales la mayoría no tienen que ver con la historia.
Finalmente hay muchos conflictos para realizar el merge.

2022-07-28 18:42 UTC, LucasfVarela commented
![2022-07-28 (1)](https://user-images.githubusercontent.com/100593063/181613766-fcca9ad6-83b0-4af6-ae19-8429b92f5955.png)
![2022-07-28 (2)](https://user-images.githubusercontent.com/100593063/181613792-f3d89675-1059-4914-aa97-a2d4574ff61e.png)

2022-07-28 18:45 UTC, LucasfVarela commented
Los Cambios son los que tuve que hacer para que funcione.

2022-07-28 19:46 UTC, emmanuelranone requested changes
Fijate que me mandas muchos archivos con cambios que no son propios de la historia

2022-07-29 11:40 UTC, emmanuelranone approved these changes

2022-07-29 11:40 UTC, merged